import Foundation

public struct Devices {
    
    /// Autogenerated
//    lazy var airpods: LazySequence<[Airpod]> = {
//        [
//            .init(generation: "AirPods (1st generation)", aNumber: ["A1523 (right AirPod)", "A1722 (left AirPod)", "A1602 (charging case)"], bootrom: "Unknown", fccID: ["BCG-A1523", "BCG-A1722"], internalName: "B188AP", identifier: ["AirPods1,1"], model: ["MMEF2"]),
//            .init(generation: "AirPods (2nd generation)", aNumber: ["A2031 (left AirPod)", "A2032 (right AirPod)", "A1938 (wireless charging case)"], bootrom: "Unknown", fccID: ["BCG-A2031", "BCG-A2032"], internalName: "B288AP", identifier: ["AirPods2,1"], model: ["MRXJ2", "MV7N2", "MR8U2"]),
//            .init(generation: "AirPods Pro", aNumber: ["A2083 (left AirPod)", "A2084 (right AirPod)", "A2190 (AirPods Pro charging case)"], bootrom: "Unknown", fccID: ["BCG-A2083", "BCG-A2084"], internalName: "B298AP", identifier: ["AirPods2,2", "iProd8,1"], model: ["MWP22"]),
//            .init(generation: "AirPods Max", aNumber: ["A2096"], bootrom: "Unknown", fccID: ["BCG-A2096"], internalName: "B515AP", identifier: ["iProd8,6"], model: ["MGYH3", "MGYJ3", "MGYL3", "MGYM3", "MGYN3"]),
//        ].lazy
//    }()
    
    public init() {
    }
}
